spring:
  application:
    name: ludoteca
  datasource:
    driver-class-name: org.postgresql.Driver
    username: gwvmptardcckaq
    password: c1375d4216d72e1081b1c85fba1fee88a7c138a70a5a7e0fa0e5626c9b4e1cb6
    url: "jdbc:postgresql://ec2-52-204-213-254.compute-1.amazonaws.com:5432/d2n03kk0664svh?sslmode=require"
  jpa:
    show-sql: true
    database: postgresql
    databese-platform: org.hibernate.dialect.PostgreSQLDialcet
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
server:
  port: 8091