package com.ludo.ludoteca.persistence.entity;

public enum Subjects {
    GENERAL, ARTES, BIOLOGIA, EDUCACION_FISICA, ESPANOL, ETICA, FISICA, INFORMATICA, INGLES, MATEMATICAS, QUIMICA, RELIGION, SOCIALES, TECNOLOGIA
}
